---
title: "TareaR1"
author: "Roy Cerda"
date: '2022-02-27'
output: html_document
---

```{r Bloque 1}

ciudad <- "Tena"
ciudad
```

```{r Bloque 2}
paises_andes <- c("Colombia","Ecuador","Peru","Bolivia","Venezuela","Argentina","Chile")
paises_andes
```

```{r Bloque 3}
poblacion_provincias_Ecuador <- data.frame(identador=seq(1:12),
                                           norte_sur=as.factor(c(rep(0, 10),1,1)),
                                           provincias=c("Guayas","Pichincha","Manabi","Azuay","Los Rios","El Oro","Tungurahua","Chimborazo","Loja","Esmeralda","Imbabura","Napo"),
                                           Habitantes=c(3073118,2254462,1192870,646344,636641,521383,449457,409568,392431,391012,360030,82085))

poblacion_provincias_Ecuador
```  

```{r Bloque 4}
library(dplyr)
df1 <- data.frame(DNase)
first_filter <- filter(data.frame(DNase), conc < 0.2 & conc > 0.1)
second_filter <- filter(data.frame(DNase), Run != 2 & conc > 0.2 & density <=1)
conc <- filter(df1, conc <0.2 & conc > 0.1)

first_filter
second_filter
conc
```

 



